### ISSUE TITLE
Add functionality for Find Application

### ISSUE THREAD

**Issue by jacksonhill7479** [Calvin-Bonomo/CSCI3308_Project#37]

**Comment by Technostalgic** [comment]
I dont really understand what find application is supposed to be can someone explain it?

**Comment by Calvin-Bonomo** [comment]
People post links to applications w/ some extra information and we display the top 20 per page (might drop the per page if it turns out to be very difficult)

**Comment by Technostalgic** [comment]
yo @Calvin-Bonomo do you mind if I snag this one from you since I've been working on the routes for creating/deleting user's posts?

**Comment by Calvin-Bonomo** [comment]
Sure, I'll go ahead and assign it to you, but checkout my branch because I've already got 90% of the implementation for querying

**Comment by Technostalgic** [comment]
perfect, I was able to use the post partial and view/page that you made, as well as the database query. I figured out the conditional rendering too and implemented a solution that allows us to access session.user from the handlebars partials, so now we have the proper user showing up in the top right when you're logged in:  
![Image](https://github.com/user-attachments/assets/f23a7045-36a6-473e-bfaf-99a1cedf20e1) 

It was just basically you pass it as an argument to `res.render('page', {data: stuff})` so I went ahead and implemented a standard for that. you can see an example wherever `res.render` is called, like in the [home '/' route here](https://github.com/Calvin-Bonomo/CSCI3308_Project/blob/develop/ProjectSourceCode/routes/get.js#L18). Just basically always pass in `PageContext.Create(app, req)` so that we can access whatever info we need from the hbs files, or with additional data if needed in an optional 3rd parameter
